FROM node:22-alpine

RUN apk add --no-cache bash

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY frontend ./frontend
COPY vite.config.ts jsconfig.json tsconfig.json tsconfig.app.json tsconfig.node.json tsconfig.node-and-fe.json ./

ENTRYPOINT [ "/bin/sh", "-c" ]

RUN npm run build-ssr

CMD [ "node frontend/dist/ssr.js" ]

